### ISSUE TITLE
Desafio 02 da DIO python.

### ISSUE THREAD

**Issue by HimAndre** [renatosetubal/python#1]
Camarada, 

Vi sua resolução do desafio02 intermediario da DIO achei interressante o metodo que vc usou. Ficou simples e pratico. O que me estranhou e não estou conseguindo entender foi a utilização das linhas;

garrafas_cheias = N // K
garrafas_vazias = N % K

procurei por tantas horas que por fim achei um codigo que funcionasse.

**Comment by renatosetubal** [comment]
N // K  retorna a parte inteira do resultado da divisão mas ignora a parte fracionária, por exemplo se coloca 10 /3 vai retornar apenas o número 3. 
no caso de %, ele retornará o valor resto de uma divisão. Muito usado para saber se o número é par ou ímpar em lógica de programação.
